// icons.js — SVG icon components used throughout the app.
// Extracted verbatim from the original bundle; exposed as window.Icons.
(function () {
  var iconBase = {
    viewBox: "0 0 24 24",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: "2",
    strokeLinecap: "round",
    strokeLinejoin: "round"
  };
  var IconOverview = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M3 13.5 12 4l9 9.5" }), /* @__PURE__ */ React.createElement("path", { d: "M5 11v9a1 1 0 0 0 1 1h4v-6h4v6h4a1 1 0 0 0 1-1v-9" }));
  var IconLedger = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M6 3h9l4 4v13a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Z" }), /* @__PURE__ */ React.createElement("path", { d: "M9 9h6M9 13h6M9 17h3" }));
  var IconAccounts = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("rect", { x: "3", y: "6", width: "18", height: "13", rx: "2" }), /* @__PURE__ */ React.createElement("path", { d: "M3 10h18" }), /* @__PURE__ */ React.createElement("path", { d: "M7 15h4" }));
  var IconVault = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("circle", { cx: "12", cy: "12", r: "9" }), /* @__PURE__ */ React.createElement("circle", { cx: "12", cy: "12", r: "3.2" }), /* @__PURE__ */ React.createElement("path", { d: "M12 3v2.2M12 18.8V21M3 12h2.2M18.8 12H21" }));
  var IconLoan = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M4 7h12" }), /* @__PURE__ */ React.createElement("path", { d: "m12 3 4 4-4 4" }), /* @__PURE__ */ React.createElement("rect", { x: "3", y: "13", width: "18", height: "7", rx: "2" }), /* @__PURE__ */ React.createElement("path", { d: "M7 16.5h4M16.5 16.5h.01" }));
  var IconAnalytics = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M4 19V9M10 19V5M16 19v-7M21 19H3" }));
  var IconUndo = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M9 14 4 9l5-5" }), /* @__PURE__ */ React.createElement("path", { d: "M4 9h10.5a5.5 5.5 0 0 1 0 11H11" }));
  var IconRedo = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "m15 14 5-5-5-5" }), /* @__PURE__ */ React.createElement("path", { d: "M20 9H9.5a5.5 5.5 0 0 0 0 11H13" }));
  var IconDownload = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M12 3v13" }), /* @__PURE__ */ React.createElement("path", { d: "m6 11 6 6 6-6" }), /* @__PURE__ */ React.createElement("path", { d: "M5 21h14" }));
  var IconUpload = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M12 21V8" }), /* @__PURE__ */ React.createElement("path", { d: "m6 13 6-6 6 6" }), /* @__PURE__ */ React.createElement("path", { d: "M5 21h14" }));
  var IconSun = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("circle", { cx: "12", cy: "12", r: "4" }), /* @__PURE__ */ React.createElement("path", { d: "M12 2v2M12 20v2M4.2 4.2l1.4 1.4M18.4 18.4l1.4 1.4M2 12h2M20 12h2M4.2 19.8l1.4-1.4M18.4 5.6l1.4-1.4" }));
  var IconMoon = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M20 14.5A8.5 8.5 0 1 1 9.5 4a7 7 0 0 0 10.5 10.5Z" }));
  var IconTrash = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M4 7h16" }), /* @__PURE__ */ React.createElement("path", { d: "M9 7V4h6v3" }), /* @__PURE__ */ React.createElement("path", { d: "M6 7l1 13a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1l1-13" }), /* @__PURE__ */ React.createElement("path", { d: "M10 11v6M14 11v6" }));
  var IconPlus = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M12 5v14M5 12h14" }));
  var IconEdit = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M12 20h9" }), /* @__PURE__ */ React.createElement("path", { d: "M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4Z" }));
  var IconSearch = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("circle", { cx: "11", cy: "11", r: "7" }), /* @__PURE__ */ React.createElement("path", { d: "m21 21-4.3-4.3" }));
  var IconFilter = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M4 6h16M7 12h10M10 18h4" }));
  var IconSort = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M8 5v14M5 8l3-3 3 3M16 19V5M13 16l3 3 3-3" }));
  var IconCSV = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M6 3h9l4 4v13a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Z" }), /* @__PURE__ */ React.createElement("path", { d: "M9 17v-4M12 17v-4M15 17v-4" }));
  var IconTransfer = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "m16 3 4 4-4 4" }), /* @__PURE__ */ React.createElement("path", { d: "M20 7H4" }), /* @__PURE__ */ React.createElement("path", { d: "m8 21-4-4 4-4" }), /* @__PURE__ */ React.createElement("path", { d: "M4 17h16" }));
  var IconChevron = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "m9 6 6 6-6 6" }));
  var IconClose = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M6 6l12 12M18 6 6 18" }));
  var IconRates = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "m7 8 4-4 4 4" }), /* @__PURE__ */ React.createElement("path", { d: "M11 4v9" }), /* @__PURE__ */ React.createElement("path", { d: "m17 16-4 4-4-4" }), /* @__PURE__ */ React.createElement("path", { d: "M13 20v-9" }));
  var IconWallet = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M3 7a2 2 0 0 1 2-2h13a1 1 0 0 1 1 1v3" }), /* @__PURE__ */ React.createElement("rect", { x: "3", y: "7", width: "18", height: "13", rx: "2" }), /* @__PURE__ */ React.createElement("path", { d: "M16 13.5h2.5" }));
  var IconInflow = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M12 4v16" }), /* @__PURE__ */ React.createElement("path", { d: "m6 14 6 6 6-6" }));
  var IconSync = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M3 12a9 9 0 0 1 15-6.7L21 8" }), /* @__PURE__ */ React.createElement("path", { d: "M21 3v5h-5" }), /* @__PURE__ */ React.createElement("path", { d: "M21 12a9 9 0 0 1-15 6.7L3 16" }), /* @__PURE__ */ React.createElement("path", { d: "M3 21v-5h5" }));
  var IconMore = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("circle", { cx: "5", cy: "12", r: "1.5", fill: "currentColor", stroke: "none" }), /* @__PURE__ */ React.createElement("circle", { cx: "12", cy: "12", r: "1.5", fill: "currentColor", stroke: "none" }), /* @__PURE__ */ React.createElement("circle", { cx: "19", cy: "12", r: "1.5", fill: "currentColor", stroke: "none" }));
  var IconMenu = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M4 7h16M4 12h16M4 17h16", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round" }));
  var IconSettings = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("circle", { cx: "12", cy: "12", r: "3" }), /* @__PURE__ */ React.createElement("path", { d: "M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.12 2.12-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.04 1.56V20.3h-3v-.08A1.7 1.7 0 0 0 10.66 18.7a1.7 1.7 0 0 0-1.88.34l-.06.06-2.12-2.12.06-.06A1.7 1.7 0 0 0 7 15.04 1.7 1.7 0 0 0 5.44 14H5.3v-3h.14A1.7 1.7 0 0 0 7 9.96a1.7 1.7 0 0 0-.34-1.88L6.6 8.02 8.72 5.9l.06.06A1.7 1.7 0 0 0 10.66 6.3a1.7 1.7 0 0 0 1.04-1.56V4.7h3v.04A1.7 1.7 0 0 0 15.74 6.3a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.12 2.12-.06.06A1.7 1.7 0 0 0 19.4 9.96 1.7 1.7 0 0 0 20.96 11h.14v3h-.14A1.7 1.7 0 0 0 19.4 15Z" }));
  var IconTune = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M4 7h5M14 7h6M4 17h9M18 17h2M4 12h2M11 12h9" }), /* @__PURE__ */ React.createElement("circle", { cx: "11", cy: "7", r: "2" }), /* @__PURE__ */ React.createElement("circle", { cx: "16", cy: "17", r: "2" }), /* @__PURE__ */ React.createElement("circle", { cx: "8", cy: "12", r: "2" }));
  var IconTag = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M20 13 13 20 4 11V4h7Z" }), /* @__PURE__ */ React.createElement("circle", { cx: "8.5", cy: "8.5", r: "1" }));
  var IconTarget = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("circle", { cx: "12", cy: "12", r: "8" }), /* @__PURE__ */ React.createElement("circle", { cx: "12", cy: "12", r: "3" }), /* @__PURE__ */ React.createElement("path", { d: "m16 8 5-5M17 3h4v4" }));
  var IconRepayment = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M20 7v5h-5" }), /* @__PURE__ */ React.createElement("path", { d: "M19 12a7 7 0 1 1-2.05-4.95L20 10" }), /* @__PURE__ */ React.createElement("path", { d: "M8 15h6M11 12v6" }));
  var IconAddMore = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("circle", { cx: "12", cy: "12", r: "8.5" }), /* @__PURE__ */ React.createElement("path", { d: "M12 8v8M8 12h8" }));
  var IconHistory = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("path", { d: "M3 12a9 9 0 1 0 3-6.7" }), /* @__PURE__ */ React.createElement("path", { d: "M3 4v5h5" }), /* @__PURE__ */ React.createElement("path", { d: "M12 7v5l3 2" }));
  var IconCalendar = ({ className }) => /* @__PURE__ */ React.createElement("svg", { className, ...iconBase }, /* @__PURE__ */ React.createElement("rect", { x: "3", y: "5", width: "18", height: "16", rx: "2" }), /* @__PURE__ */ React.createElement("path", { d: "M16 3v4M8 3v4M3 10h18" }), /* @__PURE__ */ React.createElement("path", { d: "m9 15 2 2 4-4" }));

  window.Icons = { IconOverview,IconLedger,IconAccounts,IconVault,IconLoan,IconAnalytics,IconUndo,IconRedo,IconDownload,IconUpload,IconSun,IconMoon,IconTrash,IconPlus,IconEdit,IconSearch,IconCSV,IconTransfer,IconFilter,IconSort,IconChevron,IconClose,IconRates,IconWallet,IconInflow,IconSync,IconMore,IconMenu,IconSettings,IconTune,IconTag,IconTarget,IconCalendar,IconRepayment,IconAddMore,IconHistory };
})();
